name: JavaFormatter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          files-excluded: "project/src/test/*.*"
          commitMessage: "Reformating"
